apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: webviz-spatialdb-v1
spec:
  environments:
    - name: dev
      build:
        from: main
    - name: prod
  components:
    - name: main
      authentication:
        oauth2:
          clientId: 5247ff0a-8dce-4f38-8fcf-71e5a8a4c368
          scope: openid profile email offline_access
          setXAuthRequestHeaders: true
          setAuthorizationHeader: true
          sessionStoreType: redis
          redisStore:
            connectionUrl: redis://auth-state:6379       
      src: "./webviz_output"
      publicPort: http
      ports:
       - name: http
         port: 5000       
      environmentConfig:
        - environment: prod
          variables:
            AZURE_ACC_NAME: "dlssdfsandbox"
            AZURE_CONTAINER: "dls"

        - environment: dev
          variables:
            AZURE_ACC_NAME: "dlssdfsandbox"
            AZURE_CONTAINER: "dls"   
      secretRefs:
        azureKeyVaults:
          - name: kv-datafundamentals-dev
            path: /mnt/secrets
            items:
              - name: ssdf-spatialdb-storage-key
                envVar: AZURE_PRIMARY_KEY
    - name: auth-state
      image: bitnami/redis:6.0.16
      secrets:
        - REDIS_PASSWORD    
      ports:
        - name: redis
          port: 6379