apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: webviz-spatialdb
spec:
  environments:
    - name: dev
      build:
        from: main
    - name: prod
  components:
    - name: main
      dockerfileName: webviz_output/Dockerfile
      src: "."
      publicPort: http
      ports:
       - name: http
         port: 5000
