apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: webviz-spatialdb-v1
spec:
  environments:
    - name: dev
      build:
        from: main
    - name: prod
  components:
    - name: main
      src: "./webviz_output"
      publicPort: http
      ports:
       - name: http
         port: 5000
      resources:
        requests:
          memory: "8G"
          cpu: "50m"
        limits:
          memory: "16G"
          cpu: "1000m"         
      environmentConfig:
        - environment: prod
          variables:
            LOGG_LEVEL: "INFO"
            RUN_POD3: "FALSE"
            RUN_POD2: "TRUE"

        - environment: dev
          variables:
            AZURE_ACC_NAME: "dlssdfsandbox"
            AZURE_CONTAINER: "dls"   
      secretRefs:
        azureKeyVaults:
          - name: kv-datafundamentals-dev
            path: /mnt/secrets
            items:
              - name: ssdf-spatialdb-storage-key
                envVar: AZURE_PRIMARY_KEY
