apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: webviz-spatialdb-v1
spec:
  environments:
    - name: dev
      build:
        from: main
    - name: prod
  components:
    - name: main
      src: "./webviz_output"
      publicPort: http
      ports:
       - name: http
         port: 5000
